# Generated by Django 6.0.3 on 2026-03-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrateur',
        ),
        migrations.AddField(
            model_name='employe',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
