# Generated by Django 6.0.3 on 2026-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_materiel', models.CharField(max_length=100, unique=True, verbose_name='Numéro Matériel')),
                ('design', models.CharField(max_length=255, verbose_name='Désignation')),
                ('etat', models.CharField(choices=[('bon', 'Bon État'), ('mauvais', 'Mauvais'), ('abime', 'Abimé')], default='bon', max_length=20, verbose_name='État')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
